### PR TITLE
ref: use new prepare code and remove some old 

### LINKED ISSUE #776: Loading parquet sources with Float timestamp is broken
getting:
```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: failed to prepare batch
├╴at [/Users/eric.pinzur/src/github.com/kaskada-ai/kaskada/crates/sparrow-session/src/table.rs:150:14](https://file+.vscode-resource.vscode-cdn.net/Users/eric.pinzur/src/github.com/kaskada-ai/kaskada/crates/sparrow-session/src/table.rs:150:14)
│
├─▶ internal error
│   ╰╴at [/Users/eric.pinzur/src/github.com/kaskada-ai/kaskada/crates/sparrow-runtime/src/prepare/preparer.rs:122:18](https://file+.vscode-resource.vscode-cdn.net/Users/eric.pinzur/src/github.com/kaskada-ai/kaskada/crates/sparrow-runtime/src/prepare/preparer.rs:122:18)
│
├─▶ failed to create Parquet file reader
│   ╰╴at [/Users/eric.pinzur/src/github.com/kaskada-ai/kaskada/crates/sparrow-runtime/src/prepare.rs:79:18](https://file+.vscode-resource.vscode-cdn.net/Users/eric.pinzur/src/github.com/kaskada-ai/kaskada/crates/sparrow-runtime/src/prepare.rs:79:18)
│
╰─▶ Internal error
    ├╴at [/Users/eric.pinzur/src/github.com/kaskada-ai/kaskada/crates/sparrow-runtime/src/prepare.rs:78:18](https://file+.vscode-resource.vscode-cdn.net/Users/eric.pinzur/src/github.com/kaskada-ai/kaskada/crates/sparrow-runtime/src/prepare.rs:78:18)
    ╰╴Expected column 'ts' to be castable to Timestamp(Nanosecond, None), but Float64 was not', src/table.rs:95:24
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
---------------------------------------------------------------------------
RustPanic                                 Traceback (most recent call last)
[/var/folders/_7/czrlt9jx79n78l_zsyfwycs40000gp/T/ipykernel_50657/1098232920.py](https://file+.vscode-resource.vscode-cdn.net/var/folders/_7/czrlt9jx79n78l_zsyfwycs40000gp/T/ipykernel_50657/1098232920.py) in <cell line: 1>()
      2 # Use the "ts" column as the time associated with each row,
      3 # and the "channel" column as the entity associated with each row.
----> 4 messages = await kd.sources.Parquet.create(
      5     path = "slack-export/messages.parquet",
      6     time_column = "ts",

[~/.pyenv/versions/3.11.4/lib/python3.11/site-packages/kaskada/sources/arrow.py](https://file+.vscode-resource.vscode-cdn.net/Users/eric.pinzur/src/github.com/kaskada-ai/beep-gpt/~/.pyenv/versions/3.11.4/lib/python3.11/site-packages/kaskada/sources/arrow.py) in create(path, time_column, key_column, schema, subsort_column, grouping_name, time_unit)
    579 
    580         if path:
--> 581             await source.add_file(path)
    582         return source
    583 

[~/.pyenv/versions/3.11.4/lib/python3.11/site-packages/kaskada/sources/arrow.py](https://file+.vscode-resource.vscode-cdn.net/Users/eric.pinzur/src/github.com/kaskada-ai/beep-gpt/~/.pyenv/versions/3.11.4/lib/python3.11/site-packages/kaskada/sources/arrow.py) in add_file(self, path)
    586         path = Source._get_absolute_path(path)
    587 
--> 588         await self._ffi_table.add_parquet(path)

RustPanic: rust future panicked
```

### PR DESCRIPTION
**Pull request by jordanrfrazier**
This removes the `column_behavior` in favor of the simpler, newer prepare_batch logic. This also fixes the "floats not allowed as timestamps" behavior, since the new logic handles that. 

Closes #776

### CODE REVIEW

**Comment by bjchambers** [comment]
If this passes all the tests... that's awesome. Deletes a bunch of old code and fixes bugs. I think the one thing that we maybe lose is the ability to drop/evolve columns and such -- but I think that can be added to the existing prepare batch -- if we know the "expected" schema, we can just omit/evolve columns based on the file schema and expected schema. Definitely simpler!

**Review by bjchambers — APPROVED** [review]

File: crates/sparrow-runtime/src/prepare/preparer.rs [hunk 1]
```diff
@@ -174,8 +175,8 @@ impl Preparer {
 
         let num_rows = batch.num_rows();
         let subsort = if let Some(subsort_column_name) = subsort_column_name.as_ref() {
-            let subsort = get_required_column(&batch, subsort_column_name)?;
-            arrow::compute::cast(subsort.as_ref(), &DataType::UInt64)
+            let subsort = get_required_column(&batch, &subsort_column_name)?;
+            order_preserving_cast_to_u64(subsort)
```
Comment (bjchambers) [inline crates/sparrow-runtime/src/prepare/preparer.rs]: I'm not sure we *need* the order preserving cast here. Specifically, this would only be helpful if the user properly sorted data ahead of time and subsort wasn't a u64 and order preserving cast actually preserved order. It may actually be more limited though (eg., I don't know that order preserving cast handles `f64` to `u64`.

Since we're going to resort anyway... the only thing this means is the user can't rely on the *order* of the subsorts being meaningful if they didn't choose `u64`... but it would still work for deduplicating things.

Not sure whether we want to include this chaneg.

Comment (jordanrfrazier) [reply crates/sparrow-runtime/src/prepare/preparer.rs]: Hm yeah, I would have to add float support to that method if we wanted it. I'm okay with not having it for now, and we can add it if we need it then. I'll revert this.
